### ISSUE TITLE
Can't install the wiki

### ISSUE THREAD

**Issue by becast** [Krytic/MyBBWiki#7]
As soon as you upload the files you can't access the plugin center anymore because of those lines in PermissionHandler.php, apparently they are called even though the Wiki is not installed.

```
public function get_actions() {
        $query = $this->db->write_query(sprintf("DESCRIBE `%swiki_perms`", TABLE_PREFIX));
        $actions = [];

        while($row = $this->db->fetch_array($query)) {
            $actions[] = $row['Field'];
        }

        return $actions;
}
```

**Comment by xBloodshed** [comment]
I concur.

> MyBB has experienced an internal SQL error and cannot continue.
> 
> SQL Error:
> **1146 - Table 'db.wiki_perms' doesn't exist**
> Query:
> **DESCRIBE `wiki_perms`**

**Comment by Krytic** [comment]
Thank you for confirming (and sorry it's taken so long to acknowledge). I'll push out a fix in a couple of hours, hopefully :)

**Comment by cheekybloke** [comment]
Still got an SQL Error when trying to activate plugin:

MyBB has experienced an internal SQL error and cannot continue.

**SQL Error:
1146 - Table 'db.wiki_perms' doesn't exist
Query:
DESCRIBE wiki_perms**

Was there a fix for this yet or a solution at the least?
I can't access "Plugins" in AdminCP and any response would be appreciated!

If it helps, I upload the files from Github rather than MyBB mod site.
Thanks!

**Comment by Krytic** [comment]
Quick and dirty fix:

Find:
`public function get_actions() {`
Add After:

```
        if(!wiki_is_installed()) {
            return array();
        }
```

This oughtn't cause any problems down the track, as the wiki is always closed off when the plugin is uninstalled.

**Comment by cheekybloke** [comment]
Thank you for the fast response. Works as intended. Thank you again Krytic.

**Comment by Krytic** [comment]
Hey, no worries. This'll be pushed in the next commit I make. :)
